import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../models/note.dart';
import '../view_models/note_view_model.dart';

/**
 * A stateful widget representing a calendar-like interface for taking notes.
 * Users can navigate between dates and view/add notes for the selected date.
 */
class ChatNoteScreen extends StatefulWidget {
  final NoteViewModel noteViewModel;

  /**
   * Constructs a new [ChatNoteScreen] instance.
   *
   * @param noteViewModel The view model that manages the app's note data.
   */
  const ChatNoteScreen({Key? key, required this.noteViewModel}) : super(key: key);

  @override
  _ChatNoteScreenState createState() => _ChatNoteScreenState();
}

/**
 * The state class for [ChatNoteScreen].
 *
 * It holds the currently selected date, retrieves notes for that date,
 * and handles the logic for adding new notes and toggling note states.
 */
class _ChatNoteScreenState extends State<ChatNoteScreen> {
  /// The currently selected date for which notes are displayed.
  late DateTime _selectedDate;

  /// A list of notes filtered by [_selectedDate].
  List<Note> _filteredNotes = [];

  /// A controller for the text field where the user types a new note.
  final TextEditingController _noteController = TextEditingController();

  @override
  void initState() {
    super.initState();
    // Set _selectedDate to today with time at midnight.
    _selectedDate = DateTime.now();
    _selectedDate = DateTime(_selectedDate.year, _selectedDate.month, _selectedDate.day);
    _loadNotesForDate(_selectedDate);
  }

  /**
   * Loads the notes from the ViewModel for a specific date.
   *
   * @param date The date for which to load notes.
   */
  Future<void> _loadNotesForDate(DateTime date) async {
    await widget.noteViewModel.loadNotes();
    setState(() {
      // Filter notes based on year, month, and day.
      _filteredNotes = widget.noteViewModel.notes
          .where((note) => note.createdAt.year == date.year &&
          note.createdAt.month == date.month &&
          note.createdAt.day == date.day)
          .toList();
    });
  }

  /**
   * Checks if two DateTime objects fall on the same calendar day.
   *
   * @param date1 The first date to compare.
   * @param date2 The second date to compare.
   * @return true if both dates are on the same day, otherwise false.
   */
  bool _isSameDate(DateTime date1, DateTime date2) {
    return date1.year == date2.year &&
        date1.month == date2.month &&
        date1.day == date2.day;
  }

  /**
   * Moves the selected date one day backward.
   */
  void _goToPreviousDay() {
    setState(() {
      _selectedDate = _selectedDate.subtract(const Duration(days: 1));
    });
    _loadNotesForDate(_selectedDate);
  }

  /**
   * Moves the selected date one day forward.
   */
  void _goToNextDay() {
    setState(() {
      _selectedDate = _selectedDate.add(const Duration(days: 1));
    });
    _loadNotesForDate(_selectedDate);
  }

  /**
   * Adds a new note for the currently displayed date using the text from [_noteController].
   *
   * The note's createdAt value is set to the selected date (with time = midnight).
   */
  Future<void> _addNewNote() async {
    final text = _noteController.text.trim();
    if (text.isEmpty) return;

    // Set createdAt to the selected date (time = midnight)
    final noteDate = DateTime(_selectedDate.year, _selectedDate.month, _selectedDate.day);

    final newNote = Note(
      id: 0, // id will be auto-generated by the database.
      title: 'Note',
      content: text,
      createdAt: noteDate,
      isDone: false,
    );
    await widget.noteViewModel.addNote(newNote);
    _noteController.clear();
    _loadNotesForDate(_selectedDate);
  }

  /**
   * Toggles the done state of a note when it is tapped.
   *
   * @param note The [Note] object to toggle.
   */
  Future<void> _toggleNote(Note note) async {
    await widget.noteViewModel.toggleNoteDone(note);
    _loadNotesForDate(_selectedDate);
  }

  @override
  Widget build(BuildContext context) {
    final dateString = DateFormat('dd-MMM-yyyy').format(_selectedDate);

    return Scaffold(
      backgroundColor: const Color(0xFFFDFDFD), // Very light pastel background.
      appBar: AppBar(
        title: const Text('Postponador'),
        backgroundColor: const Color(0xFFAEDFF7), // Pastel blue.
      ),
      body: Column(
        children: [
          // Date navigation row.
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 12.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                IconButton(
                  icon: const Icon(Icons.arrow_left, size: 32),
                  onPressed: _goToPreviousDay,
                ),
                Text(
                  dateString,
                  style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                ),
                IconButton(
                  icon: const Icon(Icons.arrow_right, size: 32),
                  onPressed: _goToNextDay,
                ),
              ],
            ),
          ),
          // List of notes.
          Expanded(
            child: ListView.builder(
              padding: const EdgeInsets.symmetric(horizontal: 12.0),
              itemCount: _filteredNotes.length,
              itemBuilder: (context, index) {
                final note = _filteredNotes[index];
                return GestureDetector(
                  onTap: () => _toggleNote(note),
                  child: Container(
                    margin: const EdgeInsets.symmetric(vertical: 4.0),
                    padding: const EdgeInsets.all(12.0),
                    decoration: BoxDecoration(
                      color: const Color(0xFFFFF0F5), // Pastel pink.
                      borderRadius: BorderRadius.circular(12.0),
                      border: Border.all(
                        color: const Color(0xFFB0C4DE), // Light pastel blue-gray.
                        width: 2.0,
                      ),
                    ),
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // Displays a checkmark if done; otherwise, a bullet point.
                        Padding(
                          padding: const EdgeInsets.only(right: 8.0),
                          child: Icon(
                            note.isDone ? Icons.check_circle : Icons.fiber_manual_record,
                            color: note.isDone ? Colors.green : Colors.black54,
                            size: 20,
                          ),
                        ),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                note.content,
                                style: const TextStyle(fontSize: 16),
                              ),
                              const SizedBox(height: 4),
                              // Since createdAt is stored as midnight, we can omit the time or show it as desired.
                              Text(
                                'Created: ${DateFormat('HH:mm').format(note.createdAt)}',
                                style: const TextStyle(fontSize: 12, color: Colors.grey),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                );
              },
            ),
          ),
          // Input field for a new note.
          Container(
            margin: const EdgeInsets.all(12.0), // Adds margin from the bottom and sides.
            padding: const EdgeInsets.symmetric(horizontal: 12.0),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(8.0), // Rounded corners.
              boxShadow: [
                BoxShadow(
                  color: Colors.grey.withOpacity(0.3),
                  spreadRadius: 2,
                  blurRadius: 4,
                  offset: const Offset(0, 2),
                ),
              ],
            ),
            child: Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _noteController,
                    decoration: const InputDecoration(
                      hintText: 'Enter your note for this date...',
                      border: InputBorder.none,
                    ),
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.send, color: Colors.black54),
                  onPressed: _addNewNote,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
